### ISSUE TITLE
about yawDiffRad

### ISSUE THREAD

**Issue by HeXu1** [irapkaist/SC-LeGO-LOAM#12]
thanks a lot for this great work:

in my opinion, the yawDiffRad in the code means the  yaw  diff in local Coordinate , or the viewpoint rotation.it does not same as the accumulated drift in global system. for example, the viewpoint diff may be 180° in revisit,but it does not mean  the accumulated drift of yaw is 180 in global Coordinate. we can't initial icp with yawDiffRad directly , because the SClatestSurfKeyFrameCloud and SCnearHistorySurfKeyFrameCloudDS are global Coordinate representation. 

it seems we can get real yaw drift from the relative yaw diff in both Coordinate, that is to say RealYawDrift= LocalYawDiff-GlobalYawDiff. LocalYawDiff is yawDiffRad in the code , we can get GlobalYawDiff form the loop in global Coordinate.

so , it's not the pcl's fault~
hope for your reply , thanks for your amazing work again!

**Comment by gisbi-kim** [comment]
Ah! 

Thank you for indicating the important and clear thing. 
I understood what you said; the scan context's relative was represented in a local (sensor) coord, but the original loop closing part was in the global coord.  

My first loop closure integration (ver April 2020) was not that perfect.
so I'm currently improving this repo, and your advice absolutely would be a big help :)

Thank you!

**Comment by HeXu1** [comment]
great, that's all right.

**Comment by gisbi-kim** [comment]
Then, I close this issue and I'll notify you again when the improved version is released.
Thank you.
