### ISSUE TITLE
Dependency on ROS

### ISSUE THREAD

**Issue by rlabs-oss** [irapkaist/SC-LeGO-LOAM#13]
GTSAM isn't available for ROS Noetic release. 
CMake Error at SC-LeGO-LOAM/SC-LeGO-LOAM/LeGO-LOAM/CMakeLists.txt:25 (find_package):
  By not providing "FindGTSAM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "GTSAM", but
  CMake did not find one.

  Could not find a package configuration file provided by "GTSAM" with any of
  the following names:

    GTSAMConfig.cmake
    gtsam-config.cmake

  Add the installation prefix of "GTSAM" to CMAKE_PREFIX_PATH or set
  "GTSAM_DIR" to a directory containing one of the above files.  If "GTSAM"
  provides a separate development package or SDK, be sure it has been
  installed.
 
Is there any way to use SC-LeGO-LOAM reading from e.g .csv file(s) (x,y,z,intensity) ?

**Comment by gisbi-kim** [comment]
Hi, thank you for having an interest in our work. 

I have no experience running this repo on the Noetic, so I think I  cannot give you an answer. and also I propose you to mention the issue at the original GTSAM repository. https://github.com/borglab/gtsam

also about the second question, 
currently, SC-LeGO-LOAM supports only running on the published ROS topics. 
but I think you can easily read csv files and publish the point cloud via ros topic. 

Giseop.

**Comment by rlabs-oss** [comment]
> easily read csv files and publish the point cloud via ros topic.

Thank you I will look into this.

**Comment by gisbi-kim** [comment]
> > easily read csv files and publish the point cloud via ros topic.
> 
> Thank you I will look into this.

Yes, for example, https://github.com/gisbi-kim/mini-kitti-publisher
(it read bin not csv but the flow and the purpose is actually same (i.e., read presaved files and publish them through ros message)

**Comment by rlabs-oss** [comment]
> Yes, for example, https://github.com/gisbi-kim/mini-kitti-publisher
> (it read bin not csv but the flow and the purpose is actually same (i.e., read presaved files and publish them through ros message)

Modification of `
  # pub velodyne scan 
        scan_path = os.path.join(scan_dir, scan_names[frame_idx])
        xyzi = np.fromfile(scan_path, dtype=np.float32).reshape((-1, 4))
        scan_publisher.publish(makePointCloud2Msg(xyzi[:, :3], times[frame_idx], "KITTI", 'xyz'))
`
Looks feasible. Currently I stream points in real-time from the Livox SDK (not ROS version) and dump the points to stdout then pipe those to a process which reads the translation and pose from the realsense T265 tracking camera. That process reads from stdin, transposes/translates and writes to stdout again which is piped to a file. That pipeline runs on a pi4 connected below the lidar with its own battery. It works but due to the T265 drifting the resulting point cloud has many open loops as shown in the street lights pointed out in [this video](https://youtu.be/O5dTPKGMkRk). 
Thank you.

**Comment by rlabs-oss** [comment]
I built gtsam outside of the catkin source folder. However catkin_make reports a fatal error during the build: "LeGO-LOAM/utility.h:11:10:" fatal error: cloud_msgs/cloud_info.h: No such file or directory.

**Comment by gisbi-kim** [comment]
@rlabs-oss  
actually, the installing and running procedure of this repo is exactly the same as the original repo
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM
so could you follow the above link?

**Comment by rlabs-oss** [comment]
For Ubuntu 20.04 with ROS Noetic: 
I made a new catkin workspace and tried catkin_make with the SC-LeGo-LOAM.
The first error message was "opencv/cv.h no such file or directory."

That was fixed by removing opencv/cv.h in utility.h and replacing it with: 
```
#include "opencv2/opencv.hpp"
```
I'm happy to report SC-LeGo-LOAM now builds in ROS Noetic. (with gtsam installed before the workspace creation)

Thank you very much for your help.

**Comment by gisbi-kim** [comment]
@rlabs-oss  Cooooool! 
thank you for reporting a way to run on Noetic.

**Comment by rlabs-oss** [comment]
@gisbi-kim While the build was successful - on launching it a gtsam error was generated.
