### ISSUE TITLE
How to do localization?

### ISSUE THREAD

**Issue by yutouwd** [irapkaist/SC-LeGO-LOAM#14]
Hello @gisbi-kim,

Thanks for your previous help. I have successfully run it on our rosbag, and it can build a precise map. Can it do localization/ place recognition? Like giving a pcd map and a rosbag, output the robot's position and orientation.

**Comment by gisbi-kim** [comment]
Sorry for the late response. 

I think, 
1. you first can use the SC-LIO-SAM SC descriptor saver, (see https://github.com/gisbi-kim/SC-LIO-SAM#applications), then, you'll have a set of descriptors, and corresponding (optimized) poses. 
2. in another session, you first load all SCDs (I think you can easily implement it using a single for loop and run our SCmanager's makeAndSaveScancontextAndKeys function within the for loop) // note that you need simply modify the makeAndSaveScancontextAndKeys function because the current version takes pcl point cloud, but you now just pass the pre-loaded SCD as an eigen matrix. simple)
3. now you have your seqential queris, and call detectLoopClosureID, and the corresponding ID's pose (was saved in the step 1) in this step you will use std::pair<int ID, SomeStructPose pose>, etc.

BTW, we are in the plan to support the another-session localization using Scan Context, but the code will be published after this summer. 

Thank you.

**Comment by yutouwd** [comment]
Thank you so much for your help. I will try it.

**Comment by yutouwd** [comment]
Hi @gisbi-kim,

I have tried it, but the result is not good. If I give a SCD file and use modified detectLoopClosureID to get the correspond SCD among all the SCD files, it would return a wrong match and the distance between the two SCD file is quite large. Do I use it in a wrong way? Would you mind giving some suggestions on it? Thanks a lot.

```C++
void SCManager::makeAndSaveScancontextAndKeys( Eigen::MatrixXd sc)
{
    Eigen::MatrixXd ringkey = makeRingkeyFromScancontext( sc );
    Eigen::MatrixXd sectorkey = makeSectorkeyFromScancontext( sc );
    std::vector<float> polarcontext_invkey_vec = eig2stdvec( ringkey );

    polarcontexts_.push_back( sc ); 
    polarcontext_invkeys_.push_back( ringkey );
    polarcontext_vkeys_.push_back( sectorkey );
    polarcontext_invkeys_mat_.push_back( polarcontext_invkey_vec );
}
```

```C++
std::pair<int, float> SCManager::getLocation ( Eigen::MatrixXd sc )
{
    int loop_id { -1 }; // init with -1, -1 means no loop (== LeGO-LOAM's variable "closestHistoryFrameID")

    // auto curr_key = polarcontext_invkeys_mat_.back(); // current observation (query)
    // auto curr_desc = polarcontexts_.back(); // current observation (query)

    Eigen::MatrixXd ringkey = makeRingkeyFromScancontext( sc );
    Eigen::MatrixXd sectorkey = makeSectorkeyFromScancontext( sc );
    std::vector<float> polarcontext_invkey_vec = eig2stdvec( ringkey );

    // polarcontexts_.push_back( sc ); 
    // polarcontext_invkeys_.push_back( ringkey );
    // polarcontext_vkeys_.push_back( sectorkey );
    // polarcontext_invkeys_mat_.push_back( polarcontext_invkey_vec );

    auto curr_key = polarcontext_invkey_vec;
    auto curr_desc= sc;


    /* 
     * step 1: candidates from ringkey tree_
     */
    if( (int)polarcontext_invkeys_mat_.size() < NUM_EXCLUDE_RECENT + 1)
    {
        std::pair<int, float> result {loop_id, 0.0};
        return result; // Early return 
    }

    // tree_ reconstruction (not mandatory to make everytime)
    if( tree_making_period_conter % TREE_MAKING_PERIOD_ == 0) // to save computation cost
    {
        TicToc t_tree_construction;

        polarcontext_invkeys_to_search_.clear();
        polarcontext_invkeys_to_search_.assign( polarcontext_invkeys_mat_.begin(), polarcontext_invkeys_mat_.end() - NUM_EXCLUDE_RECENT ) ;

        polarcontext_tree_.reset(); 
        polarcontext_tree_ = std::make_unique<InvKeyTree>(PC_NUM_RING /* dim */, polarcontext_invkeys_to_search_, 10 /* max leaf */ );
        // tree_ptr_->index->buildIndex(); // inernally called in the constructor of InvKeyTree (for detail, refer the nanoflann and KDtreeVectorOfVectorsAdaptor)
        t_tree_construction.toc("Tree construction");
    }
    tree_making_period_conter = tree_making_period_conter + 1;
        
    double min_dist = 10000000; // init with somthing large
    int nn_align = 0;
    int nn_idx = 0;

    // knn search
    std::vector<size_t> candidate_indexes( NUM_CANDIDATES_FROM_TREE ); 
    std::vector<float> out_dists_sqr( NUM_CANDIDATES_FROM_TREE );

    TicToc t_tree_search;
    nanoflann::KNNResultSet<float> knnsearch_result( NUM_CANDIDATES_FROM_TREE );
    knnsearch_result.init( &candidate_indexes[0], &out_dists_sqr[0] );
    polarcontext_tree_->index->findNeighbors( knnsearch_result, &curr_key[0] /* query */, nanoflann::SearchParams(10) ); 
    t_tree_search.toc("Tree search");

    /* 
     *  step 2: pairwise distance (find optimal columnwise best-fit using cosine distance)
     */
    TicToc t_calc_dist;   
    for ( int candidate_iter_idx = 0; candidate_iter_idx < NUM_CANDIDATES_FROM_TREE; candidate_iter_idx++ )
    {
        MatrixXd polarcontext_candidate = polarcontexts_[ candidate_indexes[candidate_iter_idx] ];
        std::pair<double, int> sc_dist_result = distanceBtnScanContext( curr_desc, polarcontext_candidate ); 
        
        double candidate_dist = sc_dist_result.first;
        int candidate_align = sc_dist_result.second;

        if( candidate_dist < min_dist )
        {
            min_dist = candidate_dist;
            nn_align = candidate_align;

            nn_idx = candidate_indexes[candidate_iter_idx];
        }
    }
    t_calc_dist.toc("Distance calc");

    /* 
     * loop threshold check
     */
    if( min_dist < SC_DIST_THRES )
    {
        loop_id = nn_idx; 
    
        // std::cout.precision(3); 
        cout << "[Loop found] Nearest distance: " << min_dist << " btn " << polarcontexts_.size()-1 << " and " << nn_idx << "." << endl;
        cout << "[Loop found] yaw diff: " << nn_align * PC_UNIT_SECTORANGLE << " deg." << endl;
    }
    else
    {
        std::cout.precision(3); 
        cout << "[Not loop] Nearest distance: " << min_dist << " btn " << polarcontexts_.size()-1 << " and " << nn_idx << "." << endl;
        cout << "[Not loop] yaw diff: " << nn_align * PC_UNIT_SECTORANGLE << " deg." << endl;
    }

    // To do: return also nn_align (i.e., yaw diff)
    float yaw_diff_rad = deg2rad(nn_align * PC_UNIT_SECTORANGLE);
    std::pair<int, float> result {loop_id, yaw_diff_rad};

    return result;

}
```

**Comment by gisbi-kim** [comment]
I think the query sc is from the other session, 
and the scmanager is already made so polarcontext_tree_ can be assumed it is fixed and unchanged. 
(Am I right?)

so in this case, I think the tree remake phase is no required 
I mean this part:

    // tree_ reconstruction (not mandatory to make everytime)
    if( tree_making_period_conter % TREE_MAKING_PERIOD_ == 0) // to save computation cost
    {
        TicToc t_tree_construction;

        polarcontext_invkeys_to_search_.clear();
        polarcontext_invkeys_to_search_.assign( polarcontext_invkeys_mat_.begin(), polarcontext_invkeys_mat_.end() - NUM_EXCLUDE_RECENT ) ;

        polarcontext_tree_.reset(); 
        polarcontext_tree_ = std::make_unique<InvKeyTree>(PC_NUM_RING /* dim */, polarcontext_invkeys_to_search_, 10 /* max leaf */ );
        // tree_ptr_->index->buildIndex(); // inernally called in the constructor of InvKeyTree (for detail, refer the nanoflann and KDtreeVectorOfVectorsAdaptor)
        t_tree_construction.toc("Tree construction");
    }
    tree_making_period_conter = tree_making_period_conter + 1;
