### ISSUE TITLE
About set Loop Closure factors in performLoopClosure

### ISSUE THREAD

**Issue by Barkeno** [irapkaist/SC-LeGO-LOAM#16]
Hi, @gisbi-kim , Thanks for you work, When I read "SC loop factor (scan context)" in mapOptmization.cpp :
`icp.setInputSource(RSlatestSurfKeyFrameCloud);`
`icp.setInputTarget(RSnearHistorySurfKeyFrameCloudDS);`
the source and target cloud points set into icp are in world frame, but in next part,  define poseTo and poseFrom seems as a local frame. 
`gtsam::Pose3 poseFrom = Pose3(Rot3::RzRyRx(roll, pitch, yaw), Point3(x, y, z));`
`gtsam::Pose3 poseTo = Pose3(Rot3::RzRyRx(0.0, 0.0, 0.0), Point3(0.0, 0.0, 0.0));`
In my opinion  the `correctionCameraFrame = icp.getFinalTransformation();` and `poseFrom.between(poseTo)` are not in the same frame, so I don't think the loop closure factor you set in gtsam will get a correct result.
Can you give me the reason why you set like this? Thanks!

**Comment by gisbi-kim** [comment]
It's a kind of trick to easily stitch two frames. The detailed reason is: 

- You can think of adding a loop constraint as equal to the case of consecutive frame-to-frame ICP.
-  In this case (frame-to-frame ICP), two scans are represented in their own coordinate of time t and t+1; they are not in the same frame. for the consecutive frame-to-frame ICP, we always can consider the time t's coordinate is the origin.  
- then, here, we can get a relative pose3 (let poseFrom, but actually it means delta Pose) using ICP, and the consecutive constraint can be calculated using  poseFrom.between(poseZero) it we consider the time t's coordinate is zero (as already said). 
- to mimic this situation, for the SC-loop addition, the target submap is represented in the origin, but the query scan is NOT represented in the global frame, but the submap's coordinate
- see https://github.com/irapkaist/SC-LeGO-LOAM/blob/705367eceaef797d9b4bda1c5bb91c9a0ec771f7/SC-LeGO-LOAM/LeGO-LOAM/src/mapOptmization.cpp#L928, the pose index is not latestFrameIDLoopCloure, but SCclosestHistoryFrameID. 

I hope this could be an answer.

**Comment by Barkeno** [comment]
> h query scan and
Thanks for your answer! 
You transformed the latest cloud points by SCclosestHistoryFrameID(I didn't notice it before). Thanks!
