### ISSUE TITLE
The param configuration for OS1-32

### ISSUE THREAD

**Issue by Eric97** [irapkaist/SC-LeGO-LOAM#17]
Hello,

What should be the correct configuration for OS1-32 lidar in `utility.h`? Only changing the `N_SCAN` to 32 seems not working. Can ask how is the `groundScanInd` defined for various lidars? Thanks.

Regards,
Eric

**Comment by Eric97** [comment]
- My configuration for the OS1-32 gen2 sensor:

```
extern const int N_SCAN = 32;
extern const int Horizon_SCAN = 1024;
extern const float ang_res_x = 360.0/float(Horizon_SCAN);
extern const float ang_res_y = 45.0/float(N_SCAN-1);
extern const float ang_bottom = 22.5+0.1;
extern const int groundScanInd = 7;
```

- During the mapping, the algorithms keeps printing the following message:
> [RS] ICP fit score: 4.81
> [RS] Reject this loop (bad icp fit score, > 1.5)
> [SC] ICP fit score: 6.06
> [SC] Reject this loop (bad icp fit score, > 1.5)
> [Loop found] Nearest distance: 0.457 btn 159 and 19.
> [Loop found] yaw diff: 114 deg.
> 
> [RS] ICP fit score: 4.42
> [RS] Reject this loop (bad icp fit score, > 1.5)
> [SC] ICP fit score: 4.37
> [SC] Reject this loop (bad icp fit score, > 1.5)
> [Loop found] Nearest distance: 0.453 btn 161 and 21.
> [Loop found] yaw diff: 114 deg.

- The mapping result as below: 

![Screenshot from 2021-05-17 15-25-27](https://user-images.githubusercontent.com/6669760/118448573-ba770500-b724-11eb-8de0-f84c64180f53.png)

**Comment by gisbi-kim** [comment]
@Eric97 hi eric, sorry for the late response.
your config seems right I think... 
could you try this setting in the other repo, SC-A-LOAM?
https://github.com/gisbi-kim/SC-A-LOAM/blob/main/launch/aloam_mulran.launch

**Comment by decada-robotics** [comment]
Hi @gisbi-kim , thanks for the reply. Just update that the above configuration works for Ouster32. The previous problem was due to the tf data corruption when I was playing back the rosbag.
