### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by konnoeric** [irapkaist/SC-LeGO-LOAM#18]
Hi. Thanks for your contribution.

 I installed your project because I thought yours has better loop closure feature. I run this program but it seems that it is not even building a map. 

As you can see in the photo, it's all black. What should I do with this issue? It worked with the original Lego-LOAM. 

OS: Ubuntu 18.04 
ROS: Melodic 
Lidar: 
Velodyne VLP-16

![Screenshot from 2021-07-19 19-36-56](https://user-images.githubusercontent.com/74105724/126147981-19eb75db-d79f-4968-a1cf-00c9914b77bf.png)

![Screenshot from 2021-07-19 19-42-00](https://user-images.githubusercontent.com/74105724/126148212-ec7bd259-92c8-4ab1-9172-95ba32419c3d.png)

**Comment by gisbi-kim** [comment]
I don't have the exact fit answers, but I propose to 
1. reboot the computer and remake the catkin directory and rebuild. 
2. check the launch file and topic name is right.

or could you test your data on this project? 
https://github.com/gisbi-kim/SC-A-LOAM
it is similar but A-LOAM based.

**Comment by konnoeric** [comment]
Thank you very much for your kind reply. I will try those options and report you the results in the future.

**Comment by maciej-3** [comment]
Hi! I have also experienced the same problem. May I ask if you solved it, @konnoeric?

**Comment by konnoeric** [comment]
HI, thank you very much for your advice. So you deleted slashes in the run.launch file? Is it in  the screenshot below? Sorry I am not well known about this.

![Screenshot from 2021-08-22 18-23-22](https://user-images.githubusercontent.com/74105724/130349932-6d9cb08e-29b6-45f0-92e2-69ecaa34d975.png)
