### ISSUE TITLE
LeGO-LOAM vs SC-LeGO-LOAM

### ISSUE THREAD

**Issue by robot54** [irapkaist/SC-LeGO-LOAM#2]
Hello,

Thank you for this application of Scan Context in LeGO-LOAM.
I'm currently trying to compare the results provided by LeGO-LOAM and SC-LeGO-LOAM.
I was expecting SC-LeGO-LOAM to give better (or at least equal, when there is no large drift to correct) results than the original LeGO-LOAM, but I found out that it was often not the case. 
The trajectory yielded by SC-LeGO-LOAM is indeed often a little bit further from the ground truth than the trajectory of LeGO-LOAM (even after modifying the "utility.h" files so that both use the same parameter values). The difference is generally very small, but exists. An exemple of this behaviour on the "EU Long term dataset" (https://epan-utbm.github.io/utbm_robocar_dataset/) is given in following figure, where the ground truth trajectory is nearer to the one given by LeGO-LOAM.

<img width="499" alt="SCLL_vs_LL" src="https://user-images.githubusercontent.com/61832719/79052585-e37eb980-7c37-11ea-8dc7-16ced38c1d5c.PNG">

Do you have any idea why this could be?

I went quickly through "mapOptimization.cpp"  and I noticed that, in some cases, both the RS and SC loop closure modules could be activated at the same time. Could this not lead to 'conflicts'?

Thank you very much for your answer, I'm just trying to understand this behaviour.

Have a nice day.

**Comment by kissb2** [comment]
First I'd like to say thank you for your testing on other dataset. 

Below is my personal opinion.

1. performance 
- I think the main difference btn the original and our implementation (SC-LeGO-LOAM) is using a robust kernel. You can find GTSAM's "Cauchy" kernel is used in the mapOptimization.cpp. This makes a system not fails even with false-positive loop factors in a pose graph, but sometimes may delays map correction or requires more true-positive loop factors. I think selecting which factors is up to a user, the front-end's performance, and a target environment. For example, with a large-drift in the highly-dynamic urban environment (https://www.youtube.com/watch?v=p-NsVs8GATA&feature=youtu.be&t=436), radius-search cannot work, so global revisit detector (like SC) is required. and those additional front-end loop detector may cause false-positive loop factors, so a user enhance the back-end with robust kernel... this is the flow. Anyway, so the result may slightly different.
- so Could you try again with changing the line 1088 to 1087 in mapOptimization.cpp (i.e., using constraintNoise rather robustNoiseModel) and show me the result? I also wonder about the difference.

2. about conflicts 
- Assume the case; the current node index is 106. If SC makes edge btn node 20 and 106, and RS makes edge btn node 25 and 106. but both's calculated relatives are different and may accurate on each side (if ICP doesn't fail). So this just adds more true-positive factors to the graph (so could enhance the graph's optimized quality)

Hope I may help you.

**Comment by robot54** [comment]
Hello,

Thank you very much for this detailed answser. You helped me a lot!

I followed your recommandation and tried to apply SC-LeGO-LOAM with "constraintNoise" instead of "robustNoiseModel". Here are the results. As you mentioned, it seems to require less true-positive loop factors before updating the map. Hence, the last loop closure is also detected and used to update the map, what makes the last part of the trajectory closer to the groundtruth. I'm happy with this result.

<img width="679" alt="SCLL_vs_LL_bis" src="https://user-images.githubusercontent.com/61832719/79205831-be0fcc80-7e3e-11ea-8202-711fc5c506ab.PNG">

Thank you also for your information about 'noiseScore' and the randomness of LeGO-LOAM. I also think they could be responsible for slightly different trajectories.

Have a nice day.

**Comment by kissb2** [comment]
I'm happy to hear that. 
Thank you again for reporting the results. 

Giseop

**Comment by robot54** [comment]
Hello @kissb2 ,

Sorry for re-opening this issue, but I have a new question.
I noticed that you included a robust kernel for both the RS- and the SC-constraints (lines 1043 and 1088 of mapOptimization.cpp). Would it make sense to use a robust kernel for one type of constraint and no robust kernel for the other type (that way, 4 possible combinations would exist)? Or should we stay consistent in all cases (robust kernel for both, or robust kernel for neither of both)?

Since the original LeGO-LOAM doesn't use a robust kernel for the RS-constraints, I would like to know if it is possible to only feed the SC-constraints to the robust kernel?

Have a nice day.

**Comment by kissb2** [comment]
Would it make sense to use a robust kernel for one type of constraint and no robust kernel for the other type (that way, 4 possible combinations would exist)?  
-> Sure. The "single" graph already has mixed types of kernels; for example, the non-robust kernels are used for odometry factors ("odometryNoise") now. while the robust kernels are used for loop factors.

**Comment by Xiangzhaohong** [comment]
@robot54 hi,  could you tell my how you process the kitti HDL64E data for this test?
Thanks a lot.

**Comment by kissb2** [comment]
@Xiangzhaohong refer here. 

https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/45 

searching with the keyword "HDL" also would be helpful, at the original repository 
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues?q=is%3Aissue+hdl+is%3Aclosed

**Comment by Xiangzhaohong** [comment]
@kissb2  thanks , I will try!

**Comment by Shubham-2302** [comment]
I wanted to point out to a potential mistake in the code. 
In order to use the constraint Noise model rather than robust noise model I replaced the line 1088 with the line 1087. 

```
1087          gtSAMgraph.add(BetweenFactor<Pose3>(latestFrameIDLoopCloure, closestHistoryFrameID, poseFrom.between(poseTo), constraintNoise)); // original 
1088       // gtSAMgraph.add(BetweenFactor<Pose3>(latestFrameIDLoopCloure, SCclosestHistoryFrameID, poseFrom.between(poseTo), robustNoiseModel)); // giseop
      
```
After using catkin_make I run into 
```
"closestHistoryFrameID’ was not declared in this scope"
```
Just wanted to confirm that the closestHistoryFrameID argument in the  gtSAMgraph.add will actually be SCclosestHistoryFrameID correct?
