### ISSUE TITLE
Include error nanoflann.h 

### ISSUE THREAD

**Issue by MaxandreOgeret** [irapkaist/SC-LeGO-LOAM#3]
In the include of nanoflann [here](https://github.com/irapkaist/SC-LeGO-LOAM/blob/27eb9e3b584157d247c89c61a06333b0b6285869/SC-LeGO-LOAM/LeGO-LOAM/include/KDTreeVectorOfVectorsAdaptor.h#L31)

I believe it should be : 
```cpp
#include <nanoflann.h>
```
and not 
```cpp
#include <nanoflann.hpp>
```

Is that right ?

**Comment by kissb2** [comment]
Thank you for noticing it.
That's what I missed and the filename's typo, 
so I think to replace the name nanoflann.h to nanoflann.hpp is better.  

But the code is currently runnable right?

**Comment by MaxandreOgeret** [comment]
You're welcome, thanks for the project !
Yes it worked great when I tested it, thanks !
