### ISSUE TITLE
Using GPS fix

### ISSUE THREAD

**Issue by MaxandreOgeret** [irapkaist/SC-LeGO-LOAM#4]
Hello and thanks for this very nice project.

I wanted to know if you think it would be easy to include the GPS fix in the project for more accurate localization and avoid shifting ?

Do you think it would be useful ?

Thanks a lot !

**Comment by kissb2** [comment]
It is expected to be easily achieved by adding a gtsam gps factor appropriately when the GPS topic is subscribed. (However, gps is asynchronous with LOAM node, so it runs in the other thread seems good I think.)

However, I have not yet implemented and tested it with code-level, and I planed on my future work.
I will test it later with the oxford radar dataset (having GPS and HDL32E lidar).
 
I would be very happy if you solved that part and contributed to this repo.

Giseop.

**Comment by MaxandreOgeret** [comment]
Thanks for this answer, as I need SLAM with GPS localization I will work on it tomorrow.

By the way, is the gravity acceleration expected to be filtered from the IMU ? Or it doesn't matter ?

**Comment by kissb2** [comment]
Currently, I don't have much knowledge about IMU fusion, 
so I think you should check the original LeGO-LOAM repo's issues :)
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues?q=is%3Aissue+is%3Aclosed

**Comment by MaxandreOgeret** [comment]
I tried to look up how do to it but I am afraid I dont have the knowledge.
Would you mind telling mind telling what I would have to learn and give me some hints so I can start working on it this weekend ?

Also, do you have any idea how to make the map denser ?

**Comment by kissb2** [comment]
This good example may help you. There are both odometry factor and gps factor exist in a single graph. 
- https://github.com/dongjing3309/gtsam-examples/blob/master/cpp/examples/Pose2GPSExample.cpp

For the second question
- The point cloud you see in the RVIZ of LeGO-LOAM is a feature cloud (i.e., corner and surface). so make the feature cloud denser is not recommended for the algorithm. 
- So naively, you first should get an estimated (from SLAM) se3 trajectory, and just draw every scan's point cloud using the corresponding scan pose. simple.

**Comment by kissb2** [comment]
The recently released code, LIO-SAM, has GPS factors and would be a help. 
https://github.com/TixiaoShan/LIO-SAM
