### ISSUE TITLE
std::length_error  from the Image Projection node

### ISSUE THREAD

**Issue by JustWon** [irapkaist/SC-LeGO-LOAM#6]
Thank you for the great framework.

However, I encountered the following error when I tried to execute the run.launch with the DCC dataset.

![image](https://user-images.githubusercontent.com/14357526/80778178-7b6e2400-8ba2-11ea-99b5-7fe574613534.png)

Do you have any clue?

Thanks in advance.

Won.

**Comment by kissb2** [comment]
I don't have any precise idea about that error.

but some facts and questions:
- For other datasets, did the same error shown? (e.g., KITTI)
- imageProjection.cpp in this repo is actually the same as the original one (i.e., LeGO-LOAM's one). so would you try the same dataset on the original LeGO-LOAM code first and check it runs or not?
-   I think that error would occur within vector or string (see http://www.cplusplus.com/reference/stdexcept/length_error/). so would you debug (e.g., using std::cout) around the code block having vector or string variables, particularly resizing them?

**Comment by JustWon** [comment]
Thank you for your invaluable comment.

After debugging several points that you suggested, I just reinstalled ubuntu 18.04 and ros melodic from the scratch and it worked.. haha.. 

anyway, thank you so much.

BTW, I found out the typo in Scancontext.h at line 25 when I tried to compile it.
I guess it should be #include "nanoflann.h" -> #include "nanoflann.hpp".

**Comment by kissb2** [comment]
I'm happy to hear that and thank you for the error notice!

Enjoy the project.

**Comment by mxa1097** [comment]
@JustWon,
Hi, I also meet the same error. Do you fix it on Ubuntu 16.04? 

Thanks
Mengchi
