### ISSUE TITLE
Icp loop contrainst added in gtsam different from original?

### ISSUE THREAD

**Issue by narutojxl** [irapkaist/SC-LeGO-LOAM#7]
Hi, @irapkaist, thanks for your hardwork!
When  [use icp to caculate the constraints between history and curr keyframes given by scan-context](https://github.com/irapkaist/SC-LeGO-LOAM/blob/master/SC-LeGO-LOAM/LeGO-LOAM/src/mapOptmization.cpp#L1080):
> 

            if( isValidSCloopFactor == true ) {
                correctionCameraFrame = icp.getFinalTransformation(); // get transformation in camera frame (because points are in camera frame)
                pcl::getTranslationAndEulerAngles (correctionCameraFrame, x, y, z, roll, pitch, yaw);
                gtsam::Pose3 poseFrom = Pose3(Rot3::RzRyRx(roll, pitch, yaw), Point3(x, y, z));
                gtsam::Pose3 poseTo = Pose3(Rot3::RzRyRx(0.0, 0.0, 0.0), Point3(0.0, 0.0, 0.0));
                
                std::lock_guard<std::mutex> lock(mtx);
                // gtSAMgraph.add(BetweenFactor<Pose3>(latestFrameIDLoopCloure, closestHistoryFrameID, poseFrom.between(poseTo), constraintNoise)); // original 
                gtSAMgraph.add(BetweenFactor<Pose3>(latestFrameIDLoopCloure, SCclosestHistoryFrameID, poseFrom.between(poseTo), robustNoiseModel)); // giseop
                isam->update(gtSAMgraph);
                isam->update();
                gtSAMgraph.resize(0);
            }
It is different from the original. In original:  `poseFrom` is corrected current key frame in (X-front, Y-left, Z-up) frame and `poseTo` is history keyframe is aslo in (X-front, Y-left, Z-up) frame.  I think the third param meaning `poseFrom.between(poseTo)` of `BetweenFactor` is `poseFrom.inverse() * poseTo`. It is the pose of  history keyframe in corrected current keyframe. 
Could you please give the reason why you code like this, not like the original? Thanks for your help!

**Comment by kissb2** [comment]
You are right. 

But, for me, adding a relative (virtual) measurement (i.e., icp relative) between two (time-gapped) poses is more straightforward and simple. Also, I want to reuse the original author's code format (e.g., poseFrom.between(poseTo) ) so I wrote the code like above you copied. (so I set the poseTo as a Zero 6D for convenience). I also did a python work in a similar way (see https://github.com/kissb2/PyICP-SLAM/blob/88f7b8423ea2cdaa18b48d8dfd9ecfe76877e442/utils/PoseGraphManager.py#L46).
