### ISSUE TITLE
It does not work with my dataset

### ISSUE THREAD

**Issue by mhaboali** [irapkaist/SC-LeGO-LOAM#8]
Hi, thanks for sharing the code!

By recommendation of @kissb2, I started testing your pkg with my own dataset that has VLP-16 points and GPS/IMU data but unfortunately, I didn't manage to get it working properly. The base_link is almost stationary and moves very little moves as you can see here
![image](https://user-images.githubusercontent.com/29764281/85858508-0b53d700-b7bc-11ea-8fef-f730ba9bde44.png)

And here's the rqt_graph output
![image](https://user-images.githubusercontent.com/29764281/85858564-24f51e80-b7bc-11ea-9910-f093e41ce543.png)

And here's my tf tree
![image](https://user-images.githubusercontent.com/29764281/85858760-72718b80-b7bc-11ea-98cd-4b9368cd814f.png)

Could you help to point to the possible issue I have?

Thanks!

**Comment by kissb2** [comment]
I don't know the exact reasons but I can recommend doing:
- 1. did you change the lidar configuration? (see https://github.com/irapkaist/SC-LeGO-LOAM/blob/c69515a87f0be96cf0d77a0aa6e9b38dcc807da4/SC-LeGO-LOAM/LeGO-LOAM/include/utility.h#L66)
- 2. could you try it without IMU?

**Comment by mhaboali** [comment]
Nope I've not changed the lidar config, I'll try now.

And I tested it without the IMU data, you can see the /imu/data was published by the bag.

Thanks a lot for your reply!

**Comment by mhaboali** [comment]
Yeah now it works after changing the lidar config, I thought it was for 16 by default. 

Thanks so much, @kissb2 and I'll keep you posted on the results, I hope it'd be better than A-Loam or LeGO-Loam.

**Comment by mhaboali** [comment]
It seems it shows not-small deviation as you can see here, it was supposed to be one street not two as shown here
![image](https://user-images.githubusercontent.com/29764281/85864151-6b4e7b80-b7c4-11ea-9213-b22b76634035.png)

**Comment by kissb2** [comment]
The current implementation of this repository designed to work well under this situation:
- Enough length of same-direction-revisits ( > 50 m I think..?)

and for me, the picture you attached seems the main road is revisited in the reverse direction. 
Could you include a revisiting a places (the road) in the same direction, while you take a rosbag file..?

**Comment by mhaboali** [comment]
Yes, it was the main road in the reverse direction. How can I include the revisiting places into my bag, however, it's not possible now because I have already this rosbag and I cannot reproduce it.

**Comment by kissb2** [comment]
Then I need to improve the current system (going to the v2) hmm....
and fixing the issue you mentioned is important for the better system. 

To do so, if you don't mind, could you share your data above you captured?

if not, I'm going to work with newly making my own data of a similar path you mentioned 
but the work would go easier if you help me :)

**Comment by mhaboali** [comment]
I'm really sorry!

Unfortunately, I cannot share the current dataset I'm using. But I'm very ready to contribute with you to improve the system and work on testing with my dataset.

**Comment by kissb2** [comment]
Don't worry thank you. Then I'll close this issue.
