### ISSUE TITLE
I can't get the right TF with the vlp-16

### ISSUE THREAD

**Issue by kkkkkaiai** [irapkaist/SC-LeGO-LOAM#9]
I want to use SC-lego-loam with my own bag recorded by using vlp-16. But I meet the error

```bash
PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.6
 * /use_sim_time: False

NODES
  /
    base_link_to_camera (tf/static_transform_publisher)
    camera_init_to_map (tf/static_transform_publisher)
    featureAssociation (lego_loam/featureAssociation)
    imageProjection (lego_loam/imageProjection)
    mapOptmization (lego_loam/mapOptmization)
    rviz (rviz/rviz)
    transformFusion (lego_loam/transformFusion)

ROS_MASTER_URI=http://localhost:11311

process[rviz-1]: started with pid [29973]
process[camera_init_to_map-2]: started with pid [29974]
process[base_link_to_camera-3]: started with pid [29975]
process[imageProjection-4]: started with pid [29980]
process[featureAssociation-5]: started with pid [29986]
process[mapOptmization-6]: started with pid [29988]
process[transformFusion-7]: started with pid [29989]
[ INFO] [1594191427.579571670]: ----> Transform Fusion Started.
[ INFO] [1594191427.587020577]: ----> Feature Association Started.
[ INFO] [1594191427.630501413]: ----> Map Optimization Started.
[ INFO] [1594191427.636294159]: ----> Image Projection Started.

[ WARN] [1594191438.470807606]: MSG to TF: Quaternion Not Properly Normalized
[ WARN] [1594191438.480734284]: MSG to TF: Quaternion Not Properly Normalized
[ WARN] [1594191438.480754113]: MSG to TF: Quaternion Not Properly Normalized
[ERROR] [1594191438.494563816]: Ignoring transform for child_frame_id "laser_odom" from authority "unknown_publisher" because of a nan value in the transform (nan nan nan) (-nan -nan -nan -nan)
[ERROR] [1594191438.494615782]: Ignoring transform for child_frame_id "laser_odom" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)
[ WARN] [1594191438.494650806]: MSG to TF: Quaternion Not Properly Normalized
[ WARN] [1594191438.494672032]: MSG to TF: Quaternion Not Properly Normalized
[ERROR] [1594191438.494779152]: Ignoring transform for child_frame_id "camera" from authority "unknown_publisher" because of a nan value in the transform (nan nan nan) (-nan -nan -nan -nan)
[ERROR] [1594191438.494796025]: Ignoring transform for child_frame_id "camera" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)
```

I cant get the correct TF between camera_init and "camera,laser_odom,aft_mapped", is the reason that I can't get the correct scanContext match? I must set the wrong parameter, but I don't know how to fix.

**Comment by kissb2** [comment]
First, thank you for having interest in our system. 

1. The most frequently missed point is the lidar configuration. Did you change the lidar type at utility.h (as a default, this repository's config is set as Ouster OS1-64) ? 

2. First of all, I note that this repository is totally the same as the original LeGO-LOAM repo, except only the mapOptimization.cpp file. so could you run the original lego-loam and please report the same error occurred or not.

**Comment by kkkkkaiai** [comment]
Thanks for your reply! I have fixed the problem just now. 

The reason is that my TF model isn't followed the Lego-loam's demo. So when I subscribe the data from imu, it occurs errors.Then I changed it and the problem was solved.

I want to ask that if I want to use the imu's data whether I need to change the source code.

Thanks very much, I use this method to build a high-quality map. Looking forward to your better work in the future.

**Comment by kissb2** [comment]
I'm happy to hear that this repository helped you :)

This repository didn't consider to use IMU,
but you may like the LeGO-LOAM author's recent IMU-fusion work, LIO-SAM (https://github.com/TixiaoShan/LIO-SAM)
and also thank you for the reporting of the imu related error-fixing way.
